### ISSUE TITLE
Not working inside iframe? :S

### ISSUE THREAD

**Issue by daattali** [sunmockyang/animate-scroll-js#2]
Great little plugin, really nice!

I'm able to use it perfectly well on my webpage. But I notice that if I place my page within an iframe, then the scrolling script doesn't work. Doesn't make sense to me, but perhaps you know why that's happening? Maybe something with `window` vs `top` window?

**Comment by sunmockyang** [comment]
Hmmm interesting! I'd like to try it out myself. What browser/version are you using? Does it do the same thing in other browsers too?

**Comment by daattali** [comment]
Really sorry to waste your time, I think it's a different issue that's very specific to my usecase. Your javascript is great, no problems :)

**Comment by sunmockyang** [comment]
Oh, I see. Well best of luck! Glad to hear my stuff's useful for people
