### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by petrsimon** [sunmockyang/animate-scroll-js#3]
Hi,
thanks for sharing your work, but without a license it's useless to others ;)
Cheers

**Comment by sunmockyang** [comment]
Hi, sorry for taking so long. I chose the MIT license!! Hope that works for whatever you're working on!

**Comment by sunmockyang** [comment]
Lemme know if there's any issues

**Comment by petrsimon** [comment]
Great choice! Thanks
